In [3]:
import pandas as pd
import numpy as np
#Load data using Pandas.
df = pd.read_csv('/content/Student.csv')
df.head()

   Maths  Physics  Chemistry  Result
0     17       27         22       0
1     72       82         77       1
2     97       18         13       0
3      8       42         37       0
4     32       25         20       0

In [5]:
print("\nsummary statistics.")
print(df.describe())

print("\nMaximum_Value")
df.max()

print("\ntop 10 performers.")
top = df.nlargest(10, "Result")
print(top)


print("\nsubject-wise highest scores.")
df.sort_values(by='Result', ascending=False).head(10)


print("\nAverage of overall subjects")
df["Average"] = (df["Maths"] + df["Physics"] + df["Chemistry"])/3
print(df)

print("\nAssign grades (A, B, C, D).")
def grade(Average):
    if Average >= 90:
        return "A"
    elif Average >= 80:
        return "B"
    elif Average >= 70:
        return "C"
    elif Average >= 50:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average"].apply(grade)

print(df),


print("\nValue_Counts")
print(df.value_counts())

print("\nStudent Correlation")
df.select_dtypes(include=np.number).corr()

print("\nStudent Covariance")
df.select_dtypes(include=np.number).cov()

print("\nStudent Variance")
df.select_dtypes(include=np.number).var()

print("\nStudent Standard Deviation")
df.select_dtypes(include=np.number).std()

summary statistics.
             Maths      Physics    Chemistry       Result
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     50.842000    52.316000    52.239000     0.245000
std      29.238775    24.801114    27.397052     0.430302
min       0.000000    10.000000     5.000000     0.000000
25%      26.000000    31.000000    29.750000     0.000000
50%      51.000000    51.000000    53.000000     0.000000
75%      76.000000    74.000000    76.000000     0.000000
max     100.000000    95.000000    99.000000     1.000000

Maximum_Value

top 10 performers.
    Maths  Physics  Chemistry  Result
1      72       82         77       1
6      63       67         62       1
7      97       70         65       1
8      57       93         88       1
9      60       58         53       1
12    100       72         67       1
15     62       65         60       1
18     55       67         94       1
19     77       44         62       1
21     98       85         97       1

subject-wise highest scores.

Average of overall subjects
     Maths  Physics  Chemistry  Result    Average
0       17       27         22       0  22.000000
1       72       82         77       1  77.000000
2       97       18         13       0  42.666667
3        8       42         37       0  29.000000
4       32       25         20       0  25.666667
..     ...      ...        ...     ...        ...
995      4       48         64       0  38.666667
996     63       22         88       0  57.666667
997     90       64         43       1  65.666667
998     67       41          6       0  38.000000
999     92       74          9       0  58.333333

[1000 rows x 5 columns]

Assign grades (A, B, C, D).
     Maths  Physics  Chemistry  Result    Average Grade
0       17       27         22       0  22.000000     F
1       72       82         77       1  77.000000     C
2       97       18         13       0  42.666667     F
3        8       42         37       0  29.000000     F
4       32       25         20       0  25.666667     F
..     ...      ...        ...     ...        ...   ...
995      4       48         64       0  38.666667     F
996     63       22         88       0  57.666667     D
997     90       64         43       1  65.666667     D
998     67       41          6       0  38.000000     F
999     92       74          9       0  58.333333     D

[1000 rows x 6 columns]

Value_Counts
Maths  Physics  Chemistry  Result  Average    Grade
21     75       68         0       54.666667  D        2
68     11       10         0       29.666667  F        1
       24       35         0       42.333333  F        1
       31       55         0       51.333333  D        1
       47       48         1       54.333333  D        1
                                                      ..
34     83       39         0       52.000000  D        1
       84       74         0       64.000000  D        1
       90       18         0       47.333333  F        1
35     36       55         0       42.000000  F        1
34     10       38         0       27.333333  F        1
Name: count, Length: 999, dtype: int64

Student Correlation

Student Covariance

Student Variance

Student Standard Deviation

Maths        29.238775
Physics      24.801114
Chemistry    27.397052
Result        0.430302
Average      15.423872
dtype: float64